### ISSUE TITLE
Code: Explore > Reconciliation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1193] opened 2016-01-04 17:42 UTC
This is from the wireframe in #1192 .

PR #1200 

TODO:
* [x] Totals bar chart
* [x] Filters
* [x] List area
* [x] Display Gov Reported for each type
* [x] Display Company Reported for each type
* [x] Display Material Variance for each type
* [x] Bold/make red values that exceed material variance for a given category
* [x] Ensure data is accurate

**Comment by meiqimichelle** [comment] 2016-01-20 00:17
Review for feedback time! @usEITI @splatts @Isabelle1512 @mentastc take a look at 
https://federalist.18f.gov/preview/18F/doi-extractives-data/reconciliation/explore/reconciliation/ , first version up and ready for your thoughts.

**Comment by meiqimichelle** [comment] 2016-01-20 00:23
Question for the team: should we show the direction of the discrepancy? (+/-) Is that important? (if it *is* important, we can work with @coreycaitlin to see how best to explain what that means)

Also, please review in Chrome. We're working out some bugs in Ffx.

**Comment by splatts** [comment] 2016-01-20 17:20
@meiqimichelle Hey! I know Brian and Eric are chatting about all this, so hopefully some of this is helpful! cc @gemfarmer and @ericronne 

A few comments:
-	Is it possible to make the Company data searchable via a drop-down in the “Filter by company name” bar? If so, could we then only show the data for the company being filtered instead of laying out all the company data below (and include an “all” filter to still show all the data)? 
-	Can we make the “egg graphics” a bit bigger and more friendly on the eyes? Or, at least as friendly as the egg graphics can be… :)
-	Is it possible to shift the layout a bit so the Background/Reconciliation Results text is at the top, or at least not reserved for far-left of the screen? It makes the text seems more lengthy since we have to scroll more ;)

**Comment by gemfarmer** [comment] 2016-01-20 21:20
Hey @splatts! Thanks for the review :)

* It is definitely possible to search for company in a drop-down. In your mind, would this be instead of, or in addition to the search bar company filter? @ericronne thoughts? If we add a company drop-down, would we need to do this on rev by company as well, for consistency?
* As for the left side content, we could have it larger and on top, but it wouldn't be consistent with the layout in the other Explore pages. 
* I think what we should probably do is thin the content. I have left that untouched and was hoping to hear more about what seems necessary to have on the reconciliation explore page vs the reconciliation data page. What content seems necessary to help introduce and give context to the data that the user is "exploring"?

**Comment by gemfarmer** [comment] 2016-01-20 21:24
Also, @meiqimichelle to give some explanation for the -/+ variance split, I did it that way because it was slightly easier to do than display them as positive values only. It fills up the space more, and could feel sparse otherwise.
My main issue with displaying the variance that way is that, as we discussed, having a negative variance can be confusing, so if we decide to go forward with that, we should at least add a heading to help interpretation.

**Comment by meiqimichelle** [comment] 2016-01-21 07:01
Sigh. So I had this beautiful review comment written up, an then I closed the tab, and then....all gone. :cry: 

In short:
1) I forgot about all that left-over content from the old page! That needs to be moved/adjusted. @gemfarmer if you're otherwise paused on this, maybe I can work on that tomorrow.

2) @splatts I don't 100% understand your comment on the filter drop-down, but looking at the current interaction, I think what you mean relates to the way the 'summary' chart at the top doesn't update when you filter by company below. This leads to confusion. Also, if we were to have it all update, we'd have two versions of the same data in the 'summary' area and the 'company' area below. Is this what you meant?

3) @gemfarmer if there's no significance in the positive or negative of the variance, we should not make that info signed.

**Comment by splatts** [comment] 2016-01-21 13:30
@meiqimichelle hmmm not totally sure I'm understanding your comment about not understanding my comment :) Essentially, I'm wondering if instead of having to type in the company name you could click the box and it would show a drop down of all the companies and then you could select the one you want to see and have it jump to data about that company. Does that make sense? If not, want to talk about it live to help clarify?

**Comment by gemfarmer** [comment] 2016-01-21 16:14
@meiqimichelle I have moved on to displaying offshore names issue for now, so if you want to have a stab at the left side content today, have at it. I should be done with that shortly and can return to remove the (+/-) variance and make any other needed changes.

**Comment by ericronne** [comment] 2016-01-21 17:10
I'm tied up all day with a workshop, but should we consider splitting the content onto two pages? Not sure if this has already been discussed, i haven't been able to closely follow this thread! @meiqimichelle @gemfarmer

**Comment by meiqimichelle** [comment] 2016-01-21 18:25
Team, take a look at the preview again -- I moved much of the content to the documentation page (most of it was already there -- we had originally just pulled some of that info up to a reconciliation landing page since we didn't have an interaction ready). @coreycaitlin I think this is ready for you to look at my first-version words and ideas on how to describe what's going on on this page and improve them ;)

https://federalist.18f.gov/preview/18F/doi-extractives-data/reconciliation/explore/reconciliation/

**Comment by gemfarmer** [comment] 2016-01-21 23:36
@meiqimichelle I made the changes to reconciliation. Should be an arithmetic mean of the Variance %!

**Comment by meiqimichelle** [comment] 2016-01-22 04:39
@gemfarmer Good point, maybe median is better. Game to try that and see if it seems like a better representation of the data?

I/we also need to come up with a better title for that chart. Right now: `Total discrepancies in payments by revenue type`. I guess it should be something like... `Median discrepancies in payments by revenue type`. I originally was thinking 'total' to distinguish it from the separate company data. A very accurate description gets really wordy -- something like `Median discrepancies in payments by revenue type for all in-scope and participating companies across the U.S.` haha.

**Comment by ericronne** [comment] 2016-01-22 12:54
The top-right area was designed for a visual (map/chart); dropping all that text in there doesn't work. Let's chat @meiqimichelle, i'm traveling today but ping away, thx!

**Comment by gemfarmer** [comment] 2016-01-22 16:05
The median, but probably is a better representation of the data, which is a lot of 0% Variance.

Mean:
<img width="300" alt="screen shot 2016-01-22 at 10 03 27 am" src="https://cloud.githubusercontent.com/assets/4803473/12515750/69153b04-c0ef-11e5-8a32-aa1beb5a895a.png">

Median:
<img width="300" alt="screen shot 2016-01-22 at 10 03 00 am" src="https://cloud.githubusercontent.com/assets/4803473/12515752/6b31673c-c0ef-11e5-865b-bb83f7f3c19b.png">

**Comment by gemfarmer** [comment] 2016-01-22 16:14
@meiqimichelle Also, I see what you mean about the 'Summary" area being difficult to describe. Maybe what you had, but acknowledging that it is a summary. So: `Summary: median discrepancies in payments by revenue type`?

**Comment by meiqimichelle** [comment] 2016-01-22 16:22
@gemfarmer Oh, interesting! Would there be any tiny median if we added a decimal place? I assume there's some very small discrepancies in the median...??

**Comment by gemfarmer** [comment] 2016-01-22 16:24
My guess would be that there wouldn't be because most of the reports are exactly 0, but I'll take a look.

**Comment by meiqimichelle** [comment] 2016-01-22 16:27
Oh that's right! Ugh, math and remembering how medians work :P

**Comment by gemfarmer** [comment] 2016-01-22 16:40
Yeah, it looks like adding more decimal places wouldn't make a difference.

**Comment by gemfarmer** [comment] 2016-01-22 16:43
To get more decimal places we could remove outliers and take the mean, but that would be hard to convey. 
Even more of a mouth full:
`Median discrepancies in payments by revenue type for in-scope and participating companies with variances within two standard deviations of the mean discrepancy across the U.S.`

**Comment by meiqimichelle** [comment] 2016-01-22 17:37
Naw, nevermind. It was not a good idea :)

**Comment by gemfarmer** [comment] 2016-01-25 15:08
@meiqimichelle in your mind, what needs to get done before this branch can be merged?

**Comment by meiqimichelle** [comment] 2016-01-25 21:21
@coreycaitlin is looking at the content, and then I'm guessing @ericronne will want another pass at the design. But -- close I think!

**Comment by meiqimichelle** [comment] 2016-01-29 18:42
@gemfarmer Go ahead and merge! WOOOO! We'll take the rest of the issues in separate, erm, issues.

**Comment by gemfarmer** [comment] 2016-01-29 19:50
Closing for #1239

**Closed by gemfarmer** 2016-01-29 19:50 UTC
Labels: workflow:testing
