### ISSUE TITLE
Review options for updating/replacing makefiles

### ISSUE THREAD

**Issue by master12** [18F/doi-extractives-data#2679] opened 2018-02-28 18:44 UTC
The current makefiles do not run on windows environment. We will need to find an alternative tech to use or refactor to be windows compatible.

**Comment by coreycaitlin** [comment] 2018-02-28 18:53
related to #2654 and #2553

**Comment by master12** [comment] 2018-03-06 17:55
Excel Macros could be a better tech choice for us. 
1. All data we receive could be imported into excel.
2. Macros could be used to generate yaml files
3. Macros could possibly be used to make api calls to retrieve data and insert it directly to excel.

This would eliminate the need for the makefiles and various steps of saving csv to tsv files. Also the yaml files could be generated without having a development environment.

**Comment by jeremiak** [comment] 2018-03-07 16:09
@master12 Pardon my ignorance about macros but can we keep the macros under version control or in this repo? I think one of the advantages of the script is that it can be run on a few different machines (assuming the operator knows how to run them) so it reduces the need for things to happen on a particular machine and also allows more than one set of eyes to debug any problem with them.

I know that you are sort of going around Docker right now for performance reasons and running the ruby and JS scripts directly, but I think you could still use Docker to run the Makefiles on a Windows box.

**Comment by master12** [comment] 2018-03-07 17:26
@jeremiak macros are VB code files so yes we can use version control and make them part of this project.
The macros can be installed on any machine using Excel including Jennifer or Chris or even judy and they could potentially update data on the site themselves. (Thats a TBD)
I think the debug/data verify test could be done in excel and actually be better and more visible to the end user.
So far the makefiles have not run successfully on Windows using docker, direct install or the windows linux distribution setup.

It seems to me our current Data Management is a black box and I think excel could be a better approach to enable more people to help contribute and manage our data needs. I also think there is a possibility of working with the data retrieval team in ONRR to provide us some dev support on this as well but again that is a big assumption right now.

**Comment by jeremiak** [comment] 2018-03-08 15:53
Cool, thanks for the background info! I think that's a really compelling idea, in particular pushing some of this logic into excel so that the rest of the team can participate in the data update process.

**Comment by jennmalcolm** [comment] 2018-03-27 16:45
Duplicate of #2702 so closing.

**Closed by jennmalcolm** 2018-03-27 16:45 UTC
Labels: p2, type:data
